### ISSUE TITLE
do some load tests on test server with gatling

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#187]
https://gatling.io/

jmeter could be an option too?

**Comment by TakigiTakamura** [comment]
maybe gatling is better.
gatling is better than jmeter in performance.
gatling can output into cui, and ci friendly.

and any other tools...

- wrk
- Vegeta
- Locust

| tools | gh stars | lang | since |
| -- | --: | -- | --: |
| [wrk](https://github.com/wg/wrk) | 24,502 | C | 2012 |
| [vegeta](https://github.com/tsenart/vegeta) | 14,504 | Go | 2014 |
| [locust](https://github.com/locustio/locust) | 12,699 | Python | 2011 |
| [gatling](https://github.com/gatling/gatling) | 4,708 | Scala | 2012 |
| [jmeter](https://github.com/apache/jmeter) | 4,079 | JAVA | 1998 |

on another note, if you want to test details of javascript behavior, selenium and phantomjs is helpful.

refs.
https://www.mussyu1204.com/wordpress/it/?p=361
http://mislead.jp/1993.html
https://wonderwall.hatenablog.com/entry/load-testing-tools
