### ISSUE TITLE
keyword "export" in tts.js

### ISSUE THREAD

**Issue by pachuco** [iccanobif/gikopoi2#239]
https://github.com/iccanobif/gikopoi2/commit/ee232dae38cad5316a83b1f43f2b60b8816d007e

The keyword "export" in tts.js breaks PaleMoon/Basilisk, resulting in blank page.
SyntaxError: missing declaration after 'export'

**Comment by iccanobif** [comment]
The problem is not with "export" (we already had plenty of those in utils.js) but with using async together with it, even if palemoon does seem to support async functions in general. I think this is a palemoon bug, maybe you should report this to them.
Since that function was async only to support a feature that i never enabled anyway, I could remove the whole thing, fixing the problem.

But please please also consider not using those browsers, they're clearly not keeping up with useful web features for which we just have no viable alternative (for example webrtc for streaming and web speech api for TTS).

**Comment by pachuco** [comment]
I'll report it there also.
