### ISSUE TITLE
Single Vue component is too huge

### ISSUE THREAD

**Issue by iwasa-kosui** [iccanobif/gikopoi2#303]
We have a huge single Vue component now.
Can we make it some separated components?

1. Make it TypeScript
2. Separate to be like below
    - views
        - LoginFormView
        - PlayView
    - components
        - Button
        - Textbox
        - and so on...

**Comment by iccanobif** [comment]
Both migrating to typescript and having two separate "login" and "play" views are definitely a good idea. I think this should be the first step.
The video and audio streams section would make sense in a separate component, because their logic is separate from the rest of the game.
I would not want separate components for buttons and textboxes, those elements are already simple enough and there is no need to hide them into other components.

I understand that having a single big component seems ugly, but for a small game like gikopoipoi having too many components can add complexity without a lot of benefit.
