### ISSUE TITLE
Investigate if you're actually still receiving media in the background after dropping a stream

### ISSUE THREAD

**Issue by 2sh** [iccanobif/gikopoi2#306]
Possibly related to the situation where the streamer stops their stream but is still sending zero byte packets sometimes, connections not closing properly.

**Comment by iccanobif** [comment]
i did manage to reproduce a weird situation (the stream was supposed to be off, but firefox still acts as if it's still streaming), but I'm not quite sure of how i did it
![image](https://user-images.githubusercontent.com/414953/124389465-7dbc9880-dce7-11eb-8088-5cc94b0764f9.png)

On the other hand I found another scenario: when attempting to do a screen sharing stream, you can for example deny access to the mic but allow it to the screen, and the mic stream would stay hanging. I fixed this particular issue with commit f3e23d6 but I'll leave this issue open since I suspect there are other ways to make a stream hang.

**Comment by 2sh** [comment]
I think this is fixed now
