### ISSUE TITLE
wrong tripcode

### ISSUE THREAD

**Issue by iwamizawa-software** [iccanobif/gikopoi2#308]
correct encoding (https://ja.wikipedia.org/wiki/%E3%83%88%E3%83%AA%E3%83%83%E3%83%97_(%E9%9B%BB%E5%AD%90%E6%8E%B2%E7%A4%BA%E6%9D%BF)#%E3%83%88%E3%83%AA%E3%83%83%E3%83%97%E3%82%92%E7%94%9F%E6%88%90%E3%81%99%E3%82%8B%E4%BB%95%E7%B5%84%E3%81%BF)
#& to ◆2r2Ga7GHRc

https://github.com/KenanY/tripcode encoding
#& to ◆MhCJJ7GVT.

cause is htmlescaped key
https://github.com/KenanY/tripcode/blob/ce06901d448334fa76520166e90b20a22e02eb59/index.js#L23
resolve by remove line 23

**Comment by iccanobif** [comment]
Tested on 4chan, 4-ch, 5chan and gikopoi, interestingly 4chan and 4-ch return ◆MhCJJ7GVT. while 5chan and giko return ◆2r2Ga7GHRc

Considering that the "tripcode" library is made to implement 4chan's tripcodes we have no other option than making a fork, or maybe sending a pull request to KenanY that adds a parameter to his tripcode() function so that it can return either 4chan or 5chan compatible results.

**Comment by iwamizawa-software** [comment]
![image](https://user-images.githubusercontent.com/65465755/125147466-71609180-e166-11eb-81e9-5a48aa5dc0a3.png)
Honke is ◆2r2Ga7GHRc
Please make fork
