### ISSUE TITLE
Idea: Stream volume slider that goes above 100% like vlc

### ISSUE THREAD

**Issue by 2sh** [iccanobif/gikopoi2#409]
Instead of the boost button, to save space. Clearer..? Maybe, maybe not.
The percentage number would probably need to be displayed somewhere though, on the same line, in a tooltip, on the slider somewhere itself, dunno.

Just an idea I had, no idea how the boost actually works though so maybe not simple.

**Comment by iccanobif** [comment]
mmm, this is difficult because boost doesn't just raise the volume linearly but it also turns on a compressor exactly to avoid making streams that are already loud enough become heavily distorted and sound terrible (which is a problem that VLC has...). because the effect chain on boosted stream and non-boosted streams is fundamentally different in a way that's not even linear, I have no idea of how to gradually apply a boost while the user moves the slider from, say, 100% to 110%. I see that voicemeeter does have volume sliders like that so maybe the math for doing this does exist somewhere, but... I don't know, it'd be hard to implement and I'm afraid that people familiar with what a compressor is and how VLC volume works would be even more confused
